version: '3'
services:
    django:
        build: .
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/app
        ports:
            - "8000:8000"
        tty: true
        stdin_open: true
        dns:
            - 8.8.8.8

    scrapyd:
        build: .
        command: bash -c "cd /app/scrapy_app && scrapyd"
        volumes:
            - .:/app
        ports:
            - "6800:6800"
        tty: true
        stdin_open: true
        dns:
            - 8.8.8.8
